services:
  laravel-php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: laravel-php
    volumes:
      - ./:/var/www
    networks:
      - laravel
    depends_on:
      - laravel-db

  laravel-nginx:
    image: nginx:latest
    container_name: laravel-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-php
    networks:
      - laravel

  laravel-db:
    image: mysql:8.0
    container_name: laravel-db
    restart: always
    environment:
      MYSQL_DATABASE: api_todo_list
      MYSQL_USER: todolistuser
      MYSQL_PASSWORD: ortERSAkiEntALMaXI
      MYSQL_ROOT_PASSWORD: ortERSAkiEntALMaXI
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata: